# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=56)),
                ('uid', models.CharField(max_length=56)),
                ('crowd_id', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
                ('assert_kind', models.CharField(default='undecided', max_length=10)),
                ('md_children', models.ManyToManyField(default=None, related_name='_comment_md_children_+', to='opinion.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Crowd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=12)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=56)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=56)),
                ('text', models.TextField()),
                ('fact', models.CharField(default='undecided', max_length=15)),
                ('md_comment', models.ManyToManyField(default=None, to='opinion.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('profile', models.URLField()),
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fact', models.FloatField(default=0)),
                ('non_fact', models.FloatField(default=0)),
                ('undecided', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='mention',
            name='md_sentence',
            field=models.ManyToManyField(to='opinion.Sentence'),
        ),
        migrations.AddField(
            model_name='mention',
            name='speaker',
            field=models.ManyToManyField(to='opinion.Speaker'),
        ),
    ]
